export type PrivacyVisibility = "everyone" | "selected" | "nobody";
export type PrimeSubscriptionStatus = "inactive" | "pending" | "active" | "canceled";

export type AuthUser = {
  id: string;
  name: string;
  username: string;
  email: string;
  blockedUserIds: string[];
  bio: string;
  birthday: string;
  showLastSeen: boolean;
  lastSeenVisibility: PrivacyVisibility;
  avatarVisibility: PrivacyVisibility;
  bioVisibility: PrivacyVisibility;
  birthdayVisibility: PrivacyVisibility;
  callVisibility: PrivacyVisibility;
  forwardVisibility: PrivacyVisibility;
  groupAddVisibility: PrivacyVisibility;
  lastSeenAllowedUserIds: string[];
  avatarAllowedUserIds: string[];
  bioAllowedUserIds: string[];
  birthdayAllowedUserIds: string[];
  callAllowedUserIds: string[];
  forwardAllowedUserIds: string[];
  groupAddAllowedUserIds: string[];
  lastSeenAt: number;
  avatarUrl: string;
  bannerUrl: string;
  archiveLockEnabled: boolean;
  primeStatus: PrimeSubscriptionStatus;
  primeExpiresAt: number;
  primeAutoRenew: boolean;
};
